### ISSUE TITLE
Middleware panics when transferring tokens with 10^18 denom

### ISSUE THREAD

**Issue by mtsitrin** [strangelove-ventures/packet-forward-middleware#77]
When forwarding tokens from EVM-based chains, which use `10^18` denom, it causes an overflow in the middleware

The issue happens on `float32(token.Amount.Int64()),`

```
Apr 27 10:52:42 ip-172-31-17-38 rly[376272]: ts=2023-04-27T10:52:42.781136Z lvl=error msg="Error broadcasting packet message" src_chain_id=evmos_9000-4 dst_chain_id=35-C src_client_id=07-tendermint-85 dst_client_id=07-tendermint-18 msgError="unsupported value type" error="rpc error: code = Unknown desc = rpc error: code = Unknown desc = recovered: Int64() out of bound\nstack:\ngoroutine 8744021819 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/cosmos/cosmos-sdk/baseapp.newDefaultRecoveryMiddleware.func1({0x1cb0660, 0x2b75ce0})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/recovery.go:71 +0x27\ngithub.com/cosmos/cosmos-sdk/baseapp.newRecoveryMiddleware.func1({0x1cb0660?, 0x2b75ce0?})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/recovery.go:39 +0x30\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1cb0660, 0x2b75ce0}, 0xc02d17cb40?)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/recovery.go:28 +0x37\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x1cb0660, 0x2b75ce0}, 0x2ba8d60?)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/recovery.go:33 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/baseapp.go:632 +0xfd\npanic({0x1cb0660, 0x2b75ce0})\n\truntime/panic.go:838 +0x207\ngithub.com/cosmos/cosmos-sdk/types.Int.Int64({0xdf9f66?})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/types/int.go:162 +0x86\ngithub.com/strangelove-ventures/packet-forward-middleware/v3/router/keeper.Keeper.ForwardTransferPacket.func1()\n\tgithub.com/strangelove-ventures/packet-forward-middleware/v3@v3.0.0/router/keeper/keeper.go:291 +0x5f\ngithub.com/strangelove-ventures/packet-forward-middleware/v3/router/keeper.Keeper.ForwardTransferPacket({{0x2b82558, 0xc0014265f0}, {0x2ba7260, 0xc000253eb0}, {{0x2ba7260, 0xc000253eb0}, 0xc00012a590, {0x2b82558, 0xc001426550}, {0x2b825a8, ...}, ...}, ...}, ...)\n\tgithub.com/strangelove-ventures/packet-forward-middleware/v3@v3.0.0/router/keeper/keeper.go:301 +0x1046\ngithub.com/strangelove-ventures/packet-forward-middleware/v3/router.AppModule.OnRecvPacket({{}, {{0x2b82558, 0xc0014265f0}, {0x2ba7260, 0xc000253eb0}, {{0x2ba7260, 0xc000253eb0}, 0xc00012a590, {0x2b82558, 0xc001426550}, ...}, ...}, ...}, ...)\n\tgithub.com/strangelove-ventures/packet-forward-middleware/v3@v3.0.0/router/module.go:306 +0xadb\ngithub.com/cosmos/ibc-go/v3/modules/core/keeper.Keeper.RecvPacket({{0x0, 0x0}, {0x2ba7260, 0xc000253eb0}, {{0x2b82558, 0xc001426560}, {0x2ba7260, 0xc000253eb0}, {{0x2ba7260, 0xc000253eb0}, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v3@v3.4.0/modules/core/keeper/msg_server.go:412 +0x955\ngithub.com/cosmos/ibc-go/v3/modules/core/04-channel/types._Msg_RecvPacket_Handler.func1({0x2b9af48, 0xc141c10f90}, {0x1f63600?, 0xc0002554a0})\n\tgithub.com/cosmos/ibc-go/v3@v3.4.0/modules/core/04-channel/types/tx.pb.go:1323 +0x78\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x2b9af48, 0xc141c10f60}, {0x4c0ca6?, 0x41198b?}, 0x1ff1e60?, 0xc0e72c2270)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/msg_service_router.go:113 +0xdb\ngithub.com/cosmos/ibc-go/v3/modules/core/04-channel/types._Msg_RecvPacket_Handler({0x1fe6220?, 0xc001007680}, {0x2b9af48, 0xc141c10f60}, 0x290b518, 0xc098dc6800)\n\tgithub.com/cosmos/ibc-go/v3@v3.4.0/modules/core/04-channel/types/tx.pb.go:1325 +0x138\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x2b9aed8, 0xc00012e000}, {0x2ba8d60, 0xc02d164c80}, {{0xb, 0x0}, {0xc1450412fc, 0x4}, 0xff9bd, {0x24f5967d, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/msg_service_router.go:126 +0x3d0\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x2b9aed8, 0xc00012e000}, {0x2ba8d60, 0xc02d164c80}, {{0xb, 0x0}, {0xc1450412fc, 0x4}, 0xff9bd, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/baseapp.go:760 +0x5c5\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc000dcc380, 0x2, {0xc02d13e000, 0x1e2a, 0x1e2a})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/baseapp.go:717 +0xd0c\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(0x414307?, {0xc02d13e000?, 0x1e34be0?, 0x2b7e001?})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/test_helpers.go:23 +0x2c\ngithub.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x2bb0da8, 0xc004b597e0}, {0xc000d35c98, 0x4}, {0x2b9f520, 0xc000253eb0}, {0x2bab3c8, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/x/auth/tx/service.go:120 +0x12e\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x1ee5440?, 0xc004f029c0}, {0x2b9af48, 0xc0fd770240}, 0xc159602910, 0x0)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/types/tx/service.pb.go:910 +0x170\ngithub.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1({{0x2b9aed8, 0xc00012e000}, {0x2ba8d60, 0xc02d136600}, {{0xb, 0x0}, {0xc1450412fc, 0x4}, 0xff9bd, {0x24f5967d, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/grpcrouter.go:85 +0x22d\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0xc000dcc380, 0xc004f521e0, {{0xc02d154000, 0x1e2d, 0x4000}, {0xc1ed5928d0, 0x23}, 0xff9bd, 0x0})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/abci.go:583 +0x1cf\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc000dcc380, {{0xc02d154000, 0x1e2d, 0x4000}, {0xc1ed5928d0, 0x23}, 0xff9bd, 0x0})\n\tgithub.com/cosmos/cosmos-sdk@v0.45.10/baseapp/abci.go:427 +0x77d\ngithub.com/tendermint/tendermint/abci/client.(*localClient).QuerySync(0xc00024f320, {{0xc02d154000, 0x1e2d, 0x4000}, {0xc1ed5928d0, 0x23}, 0x0, 0x0})\n\tgithub.com/tendermint/tendermint@v0.34.22/abci/client/local_client.go:256 +0x171\ngithub.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync(0x2?, {{0xc02d154000, 0x1e2d, 0x4000}, {0xc1ed5928d0, 0x23}, 0x0, 0x0})\n\tgithub.com/tendermint/tendermint@v0.34.22/proxy/app_conn.go:159 +0x6e\ngithub.com/tendermint/tendermint/rpc/core.ABCIQuery(0x8?, {0xc1ed5928d0?, 0xc00019c780?}, {0xc02d154000?, 0x4?, 0xc00de26280?}, 0x2?, 0xb9?)\n\tgithub.com/tendermint/tendermint@v0.34.22/rpc/core/abci.go:20 +0xa6\nreflect.Value.call({0x1d86180?, 0x290d690?, 0x80?}, {0x2004638, 0x4}, {0xc02cee8200, 0x5, 0x18?})\n\treflect/value.go:556 +0x845\nreflect.Value.Call({0x1d86180?, 0x290d690?, 0x3cad?}, {0xc02cee8200, 0x5, 0x5})\n\treflect/value.go:339 +0xbf\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.makeJSONRPCHandler.func1({0x2b99240, 0xc0ebd3d2d8}, 0xc02ceeac00)\n\tgithub.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_json_handler.go:96 +0x1075\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.handleInvalidJSONRPCPaths.func1({0x2b99240?, 0xc0ebd3d2d8?}, 0x0?)\n\tgithub.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_json_handler.go:122 +0x5d\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x2b99240?, 0xc0ebd3d2d8?}, 0x54e2c8?)\n\tnet/http/server.go:2084 +0x2f\nnet/http.(*ServeMux).ServeHTTP(0xc000012540?, {0x2b99240, 0xc0ebd3d2d8}, 0xc02ceeac00)\n\tnet/http/server.go:2462 +0x149\ngithub.com/rs/cors.(*Cors).Handler.func1({0x2b99240, 0xc0ebd3d2d8}, 0xc02ceeac00)\n\tgithub.com/rs/cors@v1.8.2/cors.go:231 +0x1c4\nnet/http.HandlerFunc.ServeHTTP(0x160?, {0x2b99240?, 0xc0ebd3d2d8?}, 0x0?)\n\tnet/http/server.go:2084 +0x2f\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x2b81280?, 0xc004b59280?}, 0x414307?}, {0x2b99240?, 0xc0ebd3d2d8}, 0xc02ceeac00)\n\tgithub.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_server.go:238 +0x122\ngithub.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1({0x2b99ba0?, 0xc021775880}, 0xc02ceeac00)\n\tgithub.com/tendermint/tendermint@v0.34.22/rpc/jsonrpc/server/http_server.go:211 +0x37f\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x2b99ba0?, 0xc021775880?}, 0x413fa5?)\n\tnet/http/server.go:2084 +0x2f\nnet/http.serverHandler.ServeHTTP({0x2b83f98?}, {0x2b99ba0, 0xc021775880}, 0xc02ceeac00)\n\tnet/http/server.go:2916 +0x43b\nnet/http.(*conn).serve(0xc183bd6b40, {0x2b9af48, 0xc004e94210})\n\tnet/http/server.go:1966 +0x5d7\ncreated by net/http.(*Server).Serve\n\tnet/http/server.go:3071 +0x4db\n: panic [cosmos/cosmos-sdk@v0.45.10/baseapp/recovery.go:69] With gas wanted: '0' and gas used: '274653' : unknown request"
```

**Comment by xlab** [comment]
Since this is just a telemetry logging piece, it can be easily fixed.

https://github.com/strangelove-ventures/packet-forward-middleware/blob/136e94e98861b5e7da5f5110a52772900db32c5f/router/keeper/keeper.go#L307-L311

I think the correct approach to telemetry, in this case, is to scale to 1 (shift `wei` by 1e18, `uatom` by 1e6, etc)

**Comment by jonathanpberger** [comment]
PR here: https://github.com/strangelove-ventures/packet-forward-middleware/pull/78
